spring:
  application:
    name: gateway
  cloud:
#    默认就在localhost:8848,所以可以不用配置
#    nacos:
#      discovery: # 注册中心地址
#        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
#         开启默认的路由规则，会根据注册中心的服务名作为路径实现路由规则
          enabled: true

server:
  port: 80