spring:
  application:
    name: gateway
  cloud:
#    默认就在localhost:8848,所以可以不用配置
#    nacos:
#      discovery: # 注册中心地址
#        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
#         设置为true 开启默认的路由规则，会根据注册中心的服务名作为路径实现路由规则
          enabled: false

#         可以通过 yml 和Java配置类的方式来自定义配置路由规则
      routes:
        - id: path_route
#          uri: http://localhost:8090/
#          负载均衡，到nacos中去找服务      修改uri为 lb://服务名
          uri: lb://order
          predicates:
            - Path=/order/**
#         如此设置会把 http://localhost/order/order/info 路由到 http://localhost:8090/order/order/info
#         把 http://localhost/order/info 路由到 http://localhost:8090/order/info

#         断言测试
#            - After=2026-05-19T12:00:00.000+08:00[Asia/Shanghai]  # 需要在这个时间点后才会路由
#            - Header=X-Request-Id, \d+  # 需要携带请求头：key为X-Request-Id，值为\d+（任意个0~9数字）
#            - Method=GET  # 请求方式需为GET

#         gateway的自带filter测试
          filters:
#            - AddRequestHeader=X-Request-red, blue
#            - AddRequestParameter=red, blue
#            - AddResponseHeader=X-Response-Red, Blue
#            - StripPrefix=1 # 去掉第一个路径
#           会把 /order/order/info 路由到 /order/info

      default-filters: #  默认的全局过滤器
        - AddRequestHeader=X-Request-red, blue
        - AddRequestParameter=red, blue
        - AddResponseHeader=X-Response-Red, Blue
        - StripPrefix=1

server:
  port: 80